theme: jekyll-theme-cayman
title: **Kivlin Lab**
description: Microbial and Ecosystem Ecology @ The University of Tennessee

<body>
# Research
The Kivlin Lab researchs drivers of microbial taxonomic and functional distributions in plants and soils and how microbial communities influence ecosystem-level processing of carbon and nutrients.


# People
## Stephanie Kivlin
## Jessica Moore
Postdoctoral Researcher
Microbial and Ecosystem Ecology
## Leigh Moorhead
Postdoctoral Researcher
Disturbance Ecology

</body>
