theme: jekyll-theme-cayman
title: **Kivlin Lab**
description: Microbial and Ecosystem Ecology @ The University of Tennessee

<body>

The Kivlin Lab researchs drivers of microbial taxonomic and functional distributions in plants and soils and how microbial communities influence ecosystem-level processing of carbon and nutrients.

</body>
